#!/bin/bash -e

. ./packaging.conf


PACKAGE=`grep "^Name:" rpm/*.spec | head -n1 | sed -e "s/Name://g" -e "s/[ \t]*//g"`
UPSTREAM_VERSION=`grep "^Version:" rpm/*.spec | head -n1 | sed -e "s/Version://g" -e "s/[ \t]*//g"`

echo -e "\x1b[34m###########################################\x1b[0m"
echo -e "\x1b[34mPACKAGE:            $PACKAGE\x1b[0m"
echo -e "\x1b[34mUPSTREAM_VERSION:   $UPSTREAM_VERSION\x1b[0m"
echo -e "\x1b[34m###########################################\x1b[0m"


if [ -e $PACKAGE-$UPSTREAM_VERSION ] ; then
   rm -rf $PACKAGE-$UPSTREAM_VERSION
fi
mkdir $PACKAGE-$UPSTREAM_VERSION || exit 1


# ---------------------------------------------------------
cp ChangeLog $PACKAGE-$UPSTREAM_VERSION
cp configure $PACKAGE-$UPSTREAM_VERSION
mkdir $PACKAGE-$UPSTREAM_VERSION/src
mkdir $PACKAGE-$UPSTREAM_VERSION/src/ca
cp src/ca/*.crt   $PACKAGE-$UPSTREAM_VERSION/src/ca
# ---------------------------------------------------------

tar czvf $PACKAGE-$UPSTREAM_VERSION.tar.gz $PACKAGE-$UPSTREAM_VERSION
rm -rf $PACKAGE-$UPSTREAM_VERSION
